# lec 01: intro to jupyter notebooks

<font size = "2">
sept 01 2026

venv: create an isolated environment to avoid pkg conflicts

In [2]:
print(35/8) # normal div
print(35//8) # integer fiv
print(35%8) # mod

4.375
4
3

In [21]:
import pandas as pd
import statistics as stats
import matplotlib.pyplot as plt

carfeatures = pd.read_csv('/Users/Katieduong_1/Documents/GitHub/datasci185fall2026/Lecture_01/data/features.csv')

In [11]:
carfeatures

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [24]:
carfeatures['cylinders']

0      8
1      8
2      8
3      8
4      8
      ..
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

In [25]:
table_2 = pd.crosstab(index = carfeatures['cylinders'],columns = carfeatures['mpg'])
display(table_2)

mpg,9.0,10.0,11.0,12.0,13.0,14.0,14.5,15.0,15.5,16.0,...,39.4,40.8,40.9,41.5,43.1,43.4,44.0,44.3,44.6,46.6
cylinders,,,,,,,,,,,,,,,,,,,,,
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,4,0,5,...,0,0,0,0,0,0,0,0,0,0
8,1,2,4,6,20,19,1,12,5,8,...,0,0,0,0,0,0,0,0,0,0